version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5492:5432
    environment:
      POSTGRES_DB: questions
    volumes:
      - ./postgres_data:/var/lib/postgres/data

volumes:
  postgres_data: