spring:
  datasource:
    url: jdbc:postgresql://localhost:5492/questions
    username: example
    password: example1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update