spring:
  datasource:
    url: jdbc:postgresql://localhost:5492/questions
    username: example
    password: example1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama3-70b-8192
          temperature: 0.7