name: Deploy to Production

on:
  workflow_run:
    workflows: [ "Build and Push Docker Image" ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Application
        env:
          API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
            cd /home/ec2-user
            echo "Exporting API key as environment variable"
            export GROQ_API_KEY=${API_KEY}
            echo ${GROQ_API_KEY}
            docker-compose pull
            docker-compose up -d
            sleep 20
            docker ps
          EOF
